[connections.tidb]
dialect = "mysql"
host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
port = 4000,
user = "2Ec717sQXDXrbge.root",
password = "shGX22mUul3ECK8V",
database = "phonepe_analysis"
